package com.intuit.contentAuthoringTool.Model;

import lombok.*;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;

@DynamoDBTable(tableName = "Articles")
@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Article {

    @DynamoDBHashKey(attributeName = "articleId")
    private String articleId;

    @DynamoDBAttribute(attributeName = "articleJson")
    private String articleJson;

    @DynamoDBAttribute(attributeName = "createdAt")
    @DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.CREATE) // This generates the creation timestamp
    private Date createdAt;

}
