package com.intuit.contentAuthoringTool.Model;
import lombok.*;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;

@DynamoDBTable(tableName = "Schemas")
@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Schema {

    @DynamoDBHashKey(attributeName = "schemaId")
    @DynamoDBAutoGeneratedKey
    private String schemaId;

    @DynamoDBAttribute(attributeName = "schemaTitle")
    private String schemaTitle;

    @DynamoDBAttribute(attributeName = "schemaString")
    private String schemaString;

    @DynamoDBAttribute(attributeName = "createdAt")
    @DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.CREATE) // This generates the creation timestamp
    private Date createdAt;

    @Override
    public String toString() {
        return "Schema{" +
                "schemaId='" + schemaId + '\'' +
                ", schemaString='" + schemaString + '\'' +
                '}';
    }
}
